### ISSUE TITLE
System "graph-matrix" not found

### ISSUE THREAD

**Issue by dwheelers** [tsdye/harris-matrix#1]
When I run the hm program via Clozure CL (Windows 10 installation) with quicklisp installed (ql:quickload "hm"), I get the following error:  "Error: System "graph-matrix" not found".
I believe I followed your directions and installed the hm program correctly.  The only thing I did differently, was that I failed to change the destination folder to "quicklisp/local-projects" before downloading from github.  Therefore, I manually moved the "harris-matrix" folder to the correct destination.
Thanks,
Derek Wheeler

**Comment by tsdye** [comment]
This is fixed now.

**Comment by dwheelers** [comment]
The hm load process goes much further than before, but I'm still getting an error:
[package fl.mesh]Read error between positions 1996 and 2237 in ~/quicklisp/dists/quicklisp/software/femlisp-20171227-git/src/mesh/cell.lisp.
> Error: There is no package named "SB-MOP" .
> While executing: CCL::%PARSE-TOKEN, in process listener(1).

If this seems to be a Windows issue, what OS (Linux?) and lisp program are you using?  I will attempt to duplicate your environment to bypass the OS issue.

By the way, the new documentation is great - the .dot formatting section in itself is a must read!

Thanks,,
Derek

See below for full text of loading hm.
[HM_install_error.txt](https://github.com/tsdye/harris-matrix/files/1848890/HM_install_error.txt)

**Comment by tsdye** [comment]
Aloha Derek,

Your error occurs while loading a component of the femlisp package, which is used by graph/matrix.  According to the femlisp home page, the package is tested with SBCL and "previous versions" worked with Clozure CL--the implication being that the current version might also work with Clozure CL.

I've tested hm with SBCL on Linux and Mac OS X.  I haven't tested with Clozure CL, so can't say if the problem you're seeing is specific to Windows, or to Clozure CL.

Glad you like the documentation.  Patches are always welcome.
